@startuml

class Admin_Aendern
{

--
''Durch drücken von +NEU wird ein neuer Gegenstand angelegt
''und in das jeweilige Projekt eingefügt
GegenstandHinzufuegen

''Hier wird eine Dropdownliste geöffnet. Es können die letzten
''Ergebnisse dieser Umfrage geladen werden
OeffneErgebnisse

''Es kann der Name des Gegenstandes geädnert werden
GegenstandAendern

''Hier kann das Projekt gelöscht werden
''Außerdem werden alle früheren Ergebnisse gelöscht
GegenstandLoeschen

''Hier wird ein neuer "Bucket" hinzugefügt
''Es muss ein name für das Projekt festgelegt werden
ProjektHinzufuegen

''Es wird eine neue Gruppe angelegt.
''Es muss ein name für die Gruppe festgelegt werden
GruppeHinzufuegen

''Es kann der Name der Gruppe geändert werden
''Es können mehrere Kriterien hinzugefügt werden
''Es können mehrere Kriterien gelöscht werden
GruppeAendern

''Es kann die Gruppe gelöscht werden
''Kriterien die nur in der Gruppe sind werden gelöscht
GruppeLoeschen

''Öffnet eine Überischt der Kriterie
''In welchen Gruppen ist die Kriterie, Name
KriterieOeffnen

''Es kann der Name der Kriterie geändert werden
KriterieAendern

''Es kann die Kriterie gelöscht werden
''Es wird nur die Kriterie in der Gruppe gelöscht
KriterieLoeschen
}

class Admin_Neu
{

--

}

class Admin_Start
{

--

}

class Admin_Uebersicht
{

--

}

class Bewerter_Erfuellung
{

--

}

class Bewerter_KriterienVergleich
{

--

}

class Bewerter_Uebersicht
{

--

}

class JoinSeite
{

--

}

class Landing
{

--

}

class LoginSeite
{

--

}

class Profil_Einstellungen
{

--

}

@enduml